version: "3.4"
services:
  my_frontend:
    container_name: vue3-vite-env-inject
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 5173
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true